import { NextResponse } from 'next/server';

interface EmailAnalysisRequest {
    projectName: string;
    timing: string;
    timingReason: string;
    recommendation: string;
    marketGaps: string[];
    threats: Array<{ headline: string; reason: string }>;
    opportunities: Array<{ headline: string; reason: string }>;
    niche: string;
}

export async function POST(request: Request) {
    try {
        const webhookUrl = process.env.ACTIVEPIECES_WEBHOOK_URL;

        if (!webhookUrl) {
            return NextResponse.json({
                error: 'ActivePieces webhook not configured'
            }, { status: 500 });
        }

        const body: EmailAnalysisRequest = await request.json();

        // Format the analysis as a readable email body
        const emailBody = `
🔍 AICanary Validation Report
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 Project: ${body.projectName || 'Untitled Project'}
🎯 Niche: ${body.niche || 'Technology'}

⏰ MARKET TIMING: ${body.timing?.toUpperCase() || 'NEUTRAL'}
${body.timingReason || 'No timing assessment available.'}

💡 STRATEGIC RECOMMENDATION
${body.recommendation || 'No recommendation available.'}

🎯 MARKET GAPS YOU CAN FILL
${body.marketGaps?.length > 0 ? body.marketGaps.map(g => `• ${g}`).join('\n') : '• No specific gaps identified'}

⚠️ THREATS (${body.threats?.length || 0})
${body.threats?.length > 0 ? body.threats.map(t => `• ${t.headline}\n  → ${t.reason}`).join('\n') : '• No immediate threats detected'}

💡 OPPORTUNITIES (${body.opportunities?.length || 0})
${body.opportunities?.length > 0 ? body.opportunities.map(o => `• ${o.headline}\n  → ${o.reason}`).join('\n') : '• No specific opportunities found'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by AICanary • ${new Date().toISOString().split('T')[0]}
https://ai-canary-production.up.railway.app
        `.trim();

        // Send to ActivePieces webhook
        const response = await fetch(webhookUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                headline: `🔍 AICanary Report: ${body.projectName || 'Your Project'}`,
                subject: `AICanary Validation: ${body.timing?.toUpperCase()} timing for ${body.projectName || 'Your Project'}`,
                body: emailBody,
                timing: body.timing,
                niche: body.niche,
                threatCount: body.threats?.length || 0,
                opportunityCount: body.opportunities?.length || 0,
                timestamp: new Date().toISOString()
            })
        });

        if (!response.ok) {
            console.error('Webhook error:', await response.text());
            return NextResponse.json({
                error: 'Failed to send to ActivePieces'
            }, { status: 500 });
        }

        return NextResponse.json({
            success: true,
            message: 'Analysis report sent to your email!'
        });

    } catch (error) {
        console.error('Email analysis error:', error);
        return NextResponse.json({
            error: 'Failed to send analysis'
        }, { status: 500 });
    }
}
